### ISSUE TITLE
Notifications with unreliable registries

### ISSUE THREAD

**Issue by libaurea** [I-Al-Istannen/Lighthouse#2]
I use several registries, one of them is unfortunately rather unreliable and Lighthouse only sends the error message (`de.ialistannen.lighthouse.registry.TokenFetchException: Could not fetch token as response returned status 502`) afterwards. Would it be possible to allow successful queries (on other registries) for notification/updating?

**Comment by I-Al-Istannen** [comment]
Fixed via https://github.com/I-Al-Istannen/Lighthouse/commit/0fa774e13b25c902a789c648b3dfcce9affe8a63 on Sep 5, 2022 :P
